### ISSUE TITLE
German words have /zx/ where /ʃ/ would be correct

### ISSUE THREAD

**Issue by Jendrik3** [open-dict-data/ipa-dict#1]
For a lot of words with `sch` in the middle like `Altschulden` and `Baumschule` the `sch` is described as /zx/ where /ʃ/ would be correct. AFAIK /zx/ doesn't occur at all in German.

**Comment by dohliam** [comment]
Thanks for catching this! You're absolutely right, this looks like it might be a parsing error in [germanipa](https://github.com/kdelaney/germanipa) where it analyzes "s" and "ch" separately. Happily, this seems like something that should be easy to fix -- would you be interested in submitting a PR to replace /zx/ with /ʃ/ in the German data?
