### ISSUE TITLE
Source and license for Swahili

### ISSUE THREAD

**Issue by tbm** [open-dict-data/ipa-dict#35]
The README mentions the source of several languages but not for Swahili.

Where does the Swahili IPA come from and what is the license?

**Comment by dohliam** [comment]
@tbm From the License section of the Readme:

> All material in this repository released under the MIT license unless otherwise specified. Please note that third-party datasets retain their original licenses -- refer to the [Credits](https://github.com/open-dict-data/ipa-dict#credits) section above for details.

As suggested by the above, the Swahili IPA was created as part of the ipa-dict project and is released under the default license for this repo (MIT).

**Comment by tbm** [comment]
Yes, I saw that (sorry for not making that clear).

Would it be possible to add more information on who created the Swahili IPA?  Maybe adding some names to Credits would be an option.

**Comment by dohliam** [comment]
Thanks for the suggestion! The Swahili IPA was created internally and should be credited to the [ipa-dict](https://github.com/open-dict-data/ipa-dict/) project. This applies to all languages not in the (third party) credits section.

**Comment by tbm** [comment]
Ok, thanks for the clarification
