### ISSUE TITLE
en_UK.txt contains ɡ (U+0261)

### ISSUE THREAD

**Issue by facilitas** [open-dict-data/ipa-dict#52]
[en_UK.txt](https://github.com/open-dict-data/ipa-dict/blob/bd337a5517db5fde4a958f090f0b4fd9d88e8eb1/data/en_UK.txt)

**Comment by dohliam** [comment]
Those are IPA symbols representing the voiced velar plosive sound found in English. It looks like none of them occur outside of the phonemic notation, so this shouldn't be a problem.
