### ISSUE TITLE
fr: conférenciére

### ISSUE THREAD

**Issue by Mythral** [open-dict-data/ipa-dict#9]
kɔ̃.fe.ʁɑ̃.sjɛʁ

**Comment by dohliam** [comment]
The word _conférencière_ is already included (with the same pronunciation). The spelling "conférenciére" does not appear in the dictionary so perhaps it is an error?

**Comment by Mythral** [comment]
@dohliam I had looked at wiktionary.org for pronunciation

Specifically: 
- [conférencier](https://en.wiktionary.org/wiki/conf%C3%A9rencier) 
- [conférencière](https://en.wiktionary.org/wiki/conf%C3%A9renci%C3%A8re#French)

And it denotes the pronunciation being slightly different, conférencière ends with /ʁ/, where conférencier does not.

**Comment by dohliam** [comment]
Correct! But both _conférencier_ and _conférencière_ are already in the `fr_FR` IPA dictionary, with the same pronunciations indicated as in Wiktionary. :smile: 

    conférencier    /kɔ̃feʁɑ̃sje/
    conférencière   /kɔ̃feʁɑ̃sjɛʁ/

I assume that you looked for _conférenciére_ (note the different accent) and were unable to find it, but I think this is a typo for **conférencière** (with a grave accent, as in your link above) which is already there.

**Comment by Mythral** [comment]
Whoops, sorry about that! Yes, that is definitely my mistake.
